server:
  port: 8093
  servlet:
    context-path: /


spring:
  application:
    name: documentale-content
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/content
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/documentale-mi/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:password@localhost:8761/eureka}
#  register-with-eureka: true
#  fetch-registry: true
  instance:
    #Networking/Firewall Issues
    #Problem: The use of IP addresses instead of hostnames might bypass DNS resolution. In environments where specific routing rules,
    #firewalls, or security configurations are based on hostnames, the service might fail to communicate with other services.
    #Solution: Ensure that IP-based communication is allowed in your network configuration, including firewall rules,
    #security groups, and any other routing policies that might block IP traffic.
    #prefer-ip-address: true
    hostname: localhost