server:
  port: 8092
  servlet:
    context-path: /documentale-content


spring:
  application:
    name: documentale-content
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/doc-content
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URI:http://eureka:password@localhost:8761/eureka}
##  register-with-eureka: true
##  fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    hostname: localhost