server:
  port: 8094
  servlet:
    context-path: /documentale-print

spring:
  application:
    name: documentale-print
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/documentale-cdm/protocol/openid-connect/certs
